// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"strings"
)

const filterUsersByIDs = `-- name: FilterUsersByIDs :many
SELECT id, name, email FROM users WHERE id IN ($1);
`

type FilterUsersByIDsRow struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) FilterUsersByIDs(ctx context.Context, ids []interface{}) ([]FilterUsersByIDsRow, error) {
	query := filterUsersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterUsersByIDsRow
	for rows.Next() {
		var i FilterUsersByIDsRow
		if err := rows.Scan(&i.Column1, &i.Column2, &i.Column3); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email FROM users WHERE email = $1;
`

type GetUserByEmailRow struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) GetUserByEmail(ctx context.Context, email interface{}) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.Column1, &i.Column2, &i.Column3)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, name, email) VALUES ($1, $2, $3);
`

type InsertUserParams struct {
	ID    interface{}
	Name  interface{}
	Email interface{}
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.ID, arg.Name, arg.Email)
	return err
}
