// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, name, email FROM users WHERE id = ?;
`

type GetUserRow struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) GetUser(ctx context.Context, dollar_1 interface{}) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, dollar_1)
	var i GetUserRow
	err := row.Scan(&i.Column1, &i.Column2, &i.Column3)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email FROM users ORDER BY name;
`

type ListUsersRow struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.Column1, &i.Column2, &i.Column3); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
