// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const getCompleteOrderInfo = `-- name: GetCompleteOrderInfo :one
SELECT
    o.id,
    o.amount,
    u.id as user_id,
    u.name as user_name,
    d.id as department_id,
    d.name as department_name
FROM orders o
INNER JOIN users u ON o.user_id = u.id
INNER JOIN departments d ON u.department_id = d.id
WHERE o.id = ?;

`

type GetCompleteOrderInfoRow struct {
	ID             uint32
	Amount         float64
	UserID         uint32
	UserName       string
	DepartmentID   uint32
	DepartmentName string
}

// RIGHT JOIN
func (q *Queries) GetCompleteOrderInfo(ctx context.Context, id uint32) (GetCompleteOrderInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getCompleteOrderInfo, id)
	var i GetCompleteOrderInfoRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.UserID,
		&i.UserName,
		&i.DepartmentID,
		&i.DepartmentName,
	)
	return i, err
}

const getDepartmentsWithUsers = `-- name: GetDepartmentsWithUsers :many
SELECT
    d.id,
    d.name,
    COUNT(u.id) as user_count
FROM departments d
RIGHT JOIN users u ON d.id = u.department_id
GROUP BY d.id, d.name
ORDER BY user_count DESC;

`

type GetDepartmentsWithUsersRow struct {
	ID        sql.NullInt64
	Name      sql.NullString
	UserCount uint64
}

// Multiple CTEs (unqualified column references)
func (q *Queries) GetDepartmentsWithUsers(ctx context.Context) ([]GetDepartmentsWithUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getDepartmentsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDepartmentsWithUsersRow
	for rows.Next() {
		var i GetDepartmentsWithUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceStatus = `-- name: GetResourceStatus :many
WITH current_status AS (
    SELECT department_id, COUNT(id) as user_count, MAX(id) as latest_id
    FROM users
    WHERE id > ?
    GROUP BY department_id
),
department_details AS (
    SELECT id, name
    FROM departments
    WHERE id IN (SELECT department_id FROM users WHERE id > ?)
)
SELECT
    cs.department_id,
    cs.user_count,
    cs.latest_id,
    dd.name as department_name
FROM current_status cs
LEFT JOIN department_details dd ON cs.department_id = dd.id
ORDER BY cs.user_count DESC;
`

type GetResourceStatusRow struct {
	DepartmentID   uint32
	UserCount      uint64
	LatestID       uint32
	DepartmentName sql.NullString
}

func (q *Queries) GetResourceStatus(ctx context.Context, id uint32) ([]GetResourceStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getResourceStatus, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourceStatusRow
	for rows.Next() {
		var i GetResourceStatusRow
		if err := rows.Scan(
			&i.DepartmentID,
			&i.UserCount,
			&i.LatestID,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOrders = `-- name: GetUserOrders :many
SELECT
    u.id,
    u.name,
    o.id as order_id,
    o.amount
FROM users u
LEFT JOIN orders o ON u.id = o.user_id
WHERE u.id = ?
ORDER BY o.created_at DESC;

`

type GetUserOrdersRow struct {
	ID      uint32
	Name    string
	OrderID sql.NullInt64
	Amount  sql.NullFloat64
}

// Multiple JOINs
func (q *Queries) GetUserOrders(ctx context.Context, id uint32) ([]GetUserOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrders, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrdersRow
	for rows.Next() {
		var i GetUserOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrderID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithDepartment = `-- name: GetUserWithDepartment :many
SELECT
    u.id,
    u.name,
    d.id as department_id,
    d.name as department_name
FROM users u
INNER JOIN departments d ON u.department_id = d.id
ORDER BY u.id;

`

type GetUserWithDepartmentRow struct {
	ID             uint32
	Name           string
	DepartmentID   uint32
	DepartmentName string
}

// LEFT JOIN
func (q *Queries) GetUserWithDepartment(ctx context.Context) ([]GetUserWithDepartmentRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithDepartment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWithDepartmentRow
	for rows.Next() {
		var i GetUserWithDepartmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DepartmentID,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
